import { Controller, Get, Post, Body, UseGuards, Request, Query, ParseIntPipe, DefaultValuePipe } from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiQuery } from '@nestjs/swagger';
import { EventsService } from './events.service';
import { CreateUserActionDto } from './dto/create-user-action.dto';
import { CreateAttackEventDto } from './dto/create-attack-event.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { UserRole } from '../users/entities/user.entity';

@ApiTags('events')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller({ path: 'events', version: '1' })
export class EventsController {
  constructor(private readonly eventsService: EventsService) {}

  @Post('action')
  @ApiOperation({ summary: 'Log a user action during a scenario' })
  logAction(@Request() req: any, @Body() dto: CreateUserActionDto) {
    return this.eventsService.logAction(req.user.userId, dto);
  }

  @Post('attack')
  @UseGuards(RolesGuard)
  @Roles(UserRole.ADMIN, UserRole.ANALYST) // Simulation logs might be generated by system or admin
  @ApiOperation({ summary: 'Log a simulated attack event' })
  logAttack(@Request() req: any, @Body() dto: CreateAttackEventDto) {
    return this.eventsService.logAttack(req.user.userId, dto);
  }

  @Get('me/actions')
  @ApiOperation({ summary: 'Get my recent simulation actions' })
  getMyActions(
    @Request() req: any,
    @Query('limit', new DefaultValuePipe(20), ParseIntPipe) limit: number,
  ) {
    return this.eventsService.getRecentActions(req.user.userId, limit);
  }

  @Get('log')
  @ApiOperation({ summary: 'Get security events log' })
  @ApiQuery({ name: 'userId', required: false })
  getLog(
    @Query('limit', new DefaultValuePipe(50), ParseIntPipe) limit: number,
    @Query('userId') userId?: string,
  ) {
    return this.eventsService.getSecurityLog(userId, limit);
  }
}
